##= require ./Drawable

window.Hand = class Hand extends Drawable
  constructor: (@name, @cards, @x, @y, @orientation='horizontal', @backColor='blue') ->
    @cardImages = []
    for card in @cards
      @cardImages.push(@getImage(card))

    @creationPoints = []
    creationPoint = new Point(@x+20, @y+50) if @orientation == 'horizontal'
    creationPoint = new Point(@x+20, @y+40) if @orientation == 'vertical'
    for cardImage in @cardImages
      @creationPoints.push(creationPoint)
      creationPoint = creationPoint.offsetByX(40) if @orientation == 'horizontal'
      creationPoint = creationPoint.offsetByY(40) if @orientation == 'vertical'

  contains: (point) ->
    if !@background
      @createBackground()
    @background.contains(point)

  _draw: (context) ->
    # [@x, @y] = [0, 0] if !@x and !@y
    @createBackground()
    @drawBackground(context)
    @drawName(context)
    @refreshImages(context)

  addCard: (card) ->
    @cards.push(@cards)
    @cardImages.push(@getImage(card))
    @draw(context)

  drawName: (context) ->
    context.fillStyle = 'black'
    context.font = "14pt American Typewriter"
    context.fillText(@name, @x+20, @y+30)

  createBackground: ->
    if @orientation == 'horizontal'
      @width = (@cards.length*40)+31+40
      @height = 166
    else
      @height = (@cards.length*40)+56+55
      @width = 111
    @background = new RoundedRectangle(@x, @y, @width, @height, 10)
    return @background

  drawBackground: (context) ->
    gradient = context.createLinearGradient(@x, @y, @width, @height)
    gradient.addColorStop(0,"#D4D4D4")
    gradient.addColorStop(1,"#E3E3E3")
    context.fillStyle = gradient
    @background.draw(context)
    
  refreshImages: (context) ->
    for cardImage in @cardImages
      # _i is the default count generated by CoffeeScript
      @displayImage(context, cardImage, @creationPoints[_i])

  getImage: (card) ->
    cardImage = $("#backs_#{@backColor}")[0]
    return cardImage

  displayImage: (context, cardImage, point) ->
    cardImage.setAttribute("data-x", point.x())
    cardImage.setAttribute("data-y", point.y())
    context.drawImage(cardImage, point.x(), point.y(), 71, 96)
